### ISSUE TITLE
Officially Support Python 3

### ISSUE THREAD

**Issue by AlJohri** [unitedstates/congressional-record#35]
hi all, just opening this issue here to remind myself to fix some of the smaller unicode bugs I noticed while running the tests on python 3. @napsternxg have you had a chance to try this out on python 3 yet? any bugs?

**Comment by AlJohri** [comment]
wait, tests are already passing? https://travis-ci.org/unitedstates/congressional-record
huh well, that works for me!

**Comment by nclarkjudd** [comment]
Could you be specific about what unicode issues persist? It is possible that the test suite simply isn't testing for them.

On the other hand, there really shouldn't be much trouble to cause. When I refactored this, I set it up to pass each page through BeautifulSoup. The json parser gives you flat files full of nuggets of json, so the potential for error is small there.

The only place where I would suspect one might encounter issues after having software manage the 2-to-3 migration is in writing to csv, because I frankly forget if that is good code or something I cobbled together quickly. There aren't any tests to make sure, for e.g., that names are not mangled. Perhaps there should be ...

**Comment by AlJohri** [comment]
hi @nclarkjudd, I'm relatively sure I was thinking of openelections when I mentioned that. I was working on converting both this project and openelections-core to python3 and misremembered which one had the unicode issues in the test suite. this project should most likely be good to go!  :)
