### ISSUE TITLE
Downloader not working right now

### ISSUE THREAD

**Issue by BenQuigley** [unitedstates/congressional-record#38]
This script appears not to be working right now. Example command:

```bash
$ python -m congressionalrecord.cli 1995-01-03 1995-01-10 pg --csvpath congressional-record\output```
FileNotFoundError: [Errno 2] No such file or directory: 'output/1995/CREC-1995-01-03.zip'
```

The logs show that we're not finding the file: 

```INFO:root:No download for https://www.govinfo.gov/content/pkg/CREC-1995-01-03.zip and terminating with unexpected condition.```

I just went there myself and yep, govinfo isn't serving that way anymore. I paged through their [documentation](https://www.govinfo.gov/developers) but wasn't able to find a quick fix to get the CREC info - maybe we need an API key? Am I doing something wrong?

**Comment by BenQuigley** [comment]
Apparently `python -m congressionalrecord.cli 2018-01-03 2018-01-03 pg` is working - maybe there was just no data served up on that day.

**Comment by DawsonHoney** [comment]
I have been having this issue too. It appears to only happen on weekends an holidays where congress is not in session. Its definitely not the code that's the problem. Maybe just modify the part that skips days that aren't in session?

**Comment by nclarkjudd** [comment]
try `python -m congressionalrecord.cli 2017-01-02 2017-01-02 json`

Look at the logfile in `cr2.log`:

```
INFO:root:Logging begins
DEBUG:root:Downloader object ready with params:
DEBUG:root:end=2017-01-02, do_mode=json
INFO:root:Sending request on 2018-12-27 11:26
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.govinfo.gov:443
DEBUG:urllib3.connectionpool:https://www.govinfo.gov:443 "GET /content/pkg/CREC-2017-01-02.zip HTTP/1.1" 200 0
DEBUG:root:Request headers received with code 200
INFO:root:Considering request successful.
INFO:root:No download for https://www.govinfo.gov/content/pkg/CREC-2017-01-02.zip and terminating with unexpected condition.

INFO:root:fdsysDL received expected condition True for downloader
```

Calling `GovInfoDL` from an ipython window I see that when you ask GovInfo to give you a /pkg url that doesn't exist, it gives you a JSON response with status code 200. As written, `GovInfoDL` expects to get a non-200 status code whenever something went wrong.

So, the way to solve this problem without altering the structure of the program is to fix `GovInfoDL`. The reason why we want to do it this way is I want the program to catch and handle errors as close as possible to where they happen, rather than downstream (compare to #40)

**Comment by nclarkjudd** [comment]
Turns out I put the error handling for the request itself in `downloadRequest`, which is even deeper in the internals. 

I fixed this issue by requiring downloadRequest to get a status code of 200 *and* a non-empty response, otherwise it will return an error condition.

Thanks @BenQuigley and @DawsonHoney for your help in finding, diagnosing, and patching this bug!
